log_to_wandb: 'False'
log_to_screen: 'True'
save_checkpoint: 'True'
checkpoint_save_interval: '1'
debug_grad: 'True'
true_time: 'False'
num_data_workers: '0'
enable_amp: 'False'
compile: 'False'
gradient_checkpointing: 'False'
exp_dir: /home/lkyu/baidu/MPP
log_interval: '1'
pretrained: 'False'
project: project
group: debugging
entity: entity
drop_path: '0.1'
batch_size: '1'
max_epochs: '3'
scheduler_epochs: '-1'
epoch_size: '20'
rescale_gradients: 'False'
optimizer: adan
scheduler: cosine
warmup_steps: '5'
learning_rate: '0.0001'
weight_decay: '0.001'
n_states: '12'
state_names: "['Pressure', 'Vx', 'Vy', 'Density', 'Vx', 'Vy', 'Density', 'Pressure']"
dt: '1'
n_steps: '4'
enforce_max_steps: 'False'
accum_grad: '2'
model_type: avit
block_type: axial
time_type: attention
space_type: axial_attention
tie_fields: 'False'
embed_dim: '192'
num_heads: '3'
processor_blocks: '12'
patch_size: '[16, 16]'
bias_type: rel
train_val_test: '[0.8, 0.1, 0.1]'
augmentation: 'False'
use_all_fields: 'True'
tie_batches: 'False'
extended_names: 'False'
embedding_offset: '0'
train_data_paths: "[['/home/lkyu/baidu/PDEBench/data/2D_rdb_NA_NA', 'swe', '']]"
valid_data_paths: "[['/home/lkyu/baidu/PDEBench/data/2D_rdb_NA_NA', 'swe', '']]"
append_datasets: '[]'
startEpoch: '0'
old_exp_dir: /home/lkyu/baidu/MPP/basic_config/quick_test
experiment_dir: /home/lkyu/baidu/MPP/basic_config/quick_test
checkpoint_path: 
  /home/lkyu/baidu/MPP/basic_config/quick_test/training_checkpoints/ckpt.tar
best_checkpoint_path: 
  /home/lkyu/baidu/MPP/basic_config/quick_test/training_checkpoints/best_ckpt.tar
old_checkpoint_path: 
  /home/lkyu/baidu/MPP/basic_config/quick_test/training_checkpoints/best_ckpt.tar
resuming: 'False'
name: quick_test
